### ISSUE TITLE
steam有三种id，steamid，steamid3，stamid64，建议标一下用的是steamid3

### ISSUE THREAD

**Issue by islanddddddd** [sjtdev/koishi-plugin-dota2tracker#1]
![image](https://github.com/user-attachments/assets/381c379c-f21a-4fab-a306-55e3e30bb7a4)
我试了好几次才知道你用的是steamid3

**Comment by islanddddddd** [comment]
https://steamid.tatlead.com/
我用的这个网站

**Comment by sjtdev** [comment]
好吧之前没想到过这个问题，因为DOTA2游戏中个人页面显示的ID和在stratz登录后个人页面显示的ID都是steamid3类型
我会在readme中加入的，感谢反馈

**Comment by islanddddddd** [comment]
> 好吧之前没想到过这个问题，因为DOTA2游戏中个人页面显示的ID和在stratz登录后个人页面显示的ID都是steamid3类型
> 
> 我会在readme中加入的，感谢反馈

(*￣3￣)╭，这插件挺好玩的

**Comment by sjtdev** [comment]
(｀・ω・´) 谢谢！
