### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by JhinInn** [sjtdev/koishi-plugin-dota2tracker#2]
插件市场内安装提示要启动cron服务，但是在启动cron服务之后插件无法识别到已经激活的cron服务，无法继续完成设置。

**Comment by JhinInn** [comment]
我这里和你的提示不一样。
Cron服务在启动之后，您画红线的地方仍然提示未加载，点击右上角启动也无法正常启动，提示必需项未满足。
我用的是最新版本（4.18）的Koishi。

**Comment by JhinInn** [comment]
> > 插件市场内安装提示要启动cron服务，但是在启动cron服务之后插件无法识别到已经激活的cron服务，无法继续完成设置。
> 
> 这点似乎是koishi平台的问题，我这里也是这样，试了试其他需求cron服务的插件也有这样的提示。 其实只要确保启动了`koishi-plugin-cron`插件，dota2tracker插件详情页提示的cron服务未加载可以忽略，如图： ![image](https://private-user-images.githubusercontent.com/87354389/376130705-cc2ae4b3-9e5b-43d9-8f0b-425189ffd15c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4OTIzMTksIm5iZiI6MTcyODg5MjAxOSwicGF0aCI6Ii84NzM1NDM4OS8zNzYxMzA3MDUtY2MyYWU0YjMtOWU1Yi00M2Q5LThmMGItNDI1MTg5ZmZkMTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDA3NDY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3N2RiZDYyYzg4YjkzMGFkZjE3YzJlZDEzYWQ2MDMxYTM5YjcyZmQ1MmMxNTlhOGQxODQ1MzE0NGQ3ZGRiN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uqyzWBUGO_ICvpIBeCVR-7DB53JTIX-zmD2gt8OXy-U) 这样是可以正常使用的。

补充：
![image](https://github.com/user-attachments/assets/e3281bd7-e162-4136-ab56-c8c394103d03)
重新安装了一下插件，现在和您图示里的一样了。但是点击运行是无法运行的。

**Comment by sjtdev** [comment]
> > > 插件市场内安装提示要启动cron服务，但是在启动cron服务之后插件无法识别到已经激活的cron服务，无法继续完成设置。
> > 
> > 
> > 这点似乎是koishi平台的问题，我这里也是这样，试了试其他需求cron服务的插件也有这样的提示。 其实只要确保启动了`koishi-plugin-cron`插件，dota2tracker插件详情页提示的cron服务未加载可以忽略，如图： ![image](https://private-user-images.githubusercontent.com/87354389/376130705-cc2ae4b3-9e5b-43d9-8f0b-425189ffd15c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4OTIzMTksIm5iZiI6MTcyODg5MjAxOSwicGF0aCI6Ii84NzM1NDM4OS8zNzYxMzA3MDUtY2MyYWU0YjMtOWU1Yi00M2Q5LThmMGItNDI1MTg5ZmZkMTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDA3NDY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3N2RiZDYyYzg4YjkzMGFkZjE3YzJlZDEzYWQ2MDMxYTM5YjcyZmQ1MmMxNTlhOGQxODQ1MzE0NGQ3ZGRiN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uqyzWBUGO_ICvpIBeCVR-7DB53JTIX-zmD2gt8OXy-U) 这样是可以正常使用的。
> 
> 补充： ![image](https://private-user-images.githubusercontent.com/46416537/376146574-e3281bd7-e162-4136-ab56-c8c394103d03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4OTQwOTAsIm5iZiI6MTcyODg5Mzc5MCwicGF0aCI6Ii80NjQxNjUzNy8zNzYxNDY1NzQtZTMyODFiZDctZTE2Mi00MTM2LWFiNTYtYzhjMzk0MTAzZDAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDA4MTYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ZDgxYjhjMmViMDQ4NDk4OWYyZTkxZjU2MmJjNjIzOThhMDE5NWQxMWFhMjAxNGZmNDIwNGViNzJhOTA5MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kMn6Twxh6BhqlLgq5AQvFBzdSBN8zjXLrtid0-HOzdg) 重新安装了一下插件，现在和您图示里的一样了。但是点击运行是无法运行的。

下面插件配置项[**STRATZ_API_TOKEN**]填了吗？这项是强制要求，没有填入是启动不了的，我猜可能是因为这个问题。

**Comment by JhinInn** [comment]
当然是正确填写的。
我申请了Stratz的 Silver 级别 API。
整个页面只有cron一个地方提示未满足。
