### ISSUE TITLE
STRATZ api 限制最多一次查询5个ID，如果群内绑定人数超过5人则会报错

### ISSUE THREAD

**Issue by zhoutongmike** [sjtdev/koishi-plugin-dota2tracker#3]
原始报错
![image](https://github.com/user-attachments/assets/d454a19a-47b9-4b87-8619-c39481050449)
捕获 query 的返回值，发现报错为api限制导致
![MDG)N3C}D9K3TD@(G9_5FLB](https://github.com/user-attachments/assets/bc307020-e401-4b34-827a-8bd1dc8e8c70)
顺带一提，查询最近比赛也无法使用，但是没有任何报错，我也没有定位到问题所在
![image](https://github.com/user-attachments/assets/4bb45d70-41bc-499a-ac2c-539a3dda8981)
其他功能都正常

**Comment by sjtdev** [comment]
感谢反馈，我研究一下

**Comment by sjtdev** [comment]
@zhoutongmike 我试着修了一下，在测试环境是没什么问题了，推送了`1.2.18-beta.1`版本，可以更新试试看

**Comment by zhoutongmike** [comment]
> @zhoutongmike 我试着修了一下，在测试环境是没什么问题了，推送了`1.2.18-beta.1`版本，可以更新试试看

感谢感谢，现在都没问题了，太强了！

**Comment by sjtdev** [comment]
> > @zhoutongmike 我试着修了一下，在测试环境是没什么问题了，推送了`1.2.18-beta.1`版本，可以更新试试看
> 
> 感谢感谢，现在都没问题了，太强了！

😋 没问题等会我就推个正式版，顺便更新一下dotaconstants依赖，感谢使用。
