### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'dealtTotal')

### ISSUE THREAD

**Issue by zhoutongmike** [sjtdev/koishi-plugin-dota2tracker#4]
![image](https://github.com/user-attachments/assets/b073479e-ed5a-450a-9fbd-942924e1c82e)
在dt_previous_query_results数据库中把该场比赛数据删了重新获取就可以恢复正常

**Comment by sjtdev** [comment]
> ![image](https://private-user-images.githubusercontent.com/178678568/398934646-b073479e-ed5a-450a-9fbd-942924e1c82e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzMTk4ODEsIm5iZiI6MTczNTMxOTU4MSwicGF0aCI6Ii8xNzg2Nzg1NjgvMzk4OTM0NjQ2LWIwNzM0NzllLWVkNWEtNDUwYS05ZmJkLTk0MjkyNGUxYzgyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QxNzEzMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDI3NjU0NjJlMDQ3MzVmNTJmNTA0NzNlZDAzZWVlMDY4NzI1ODk2NzMxNTM2MWJjNzkyODJmYzIwZWQ1OTQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.A81tap9DajOws3Rd1aJS-plP8bB-ElMD4GXmD8hCy1w) 在dt_previous_query_results数据库中把该场比赛数据删了重新获取就可以恢复正常

挠头
这其实是API缺陷，因为这个问题我这里也触发过，经过排查发现等待解析中第一次获取到已解析的数据仍然可能不全，所以才会出现重新获取就正常的现象。推测数据应该是刚开始解析时就设置了parsedDateTime，导致的误判。

我明天看看如何修复吧

**Comment by sjtdev** [comment]
> ![image](https://private-user-images.githubusercontent.com/178678568/398934646-b073479e-ed5a-450a-9fbd-942924e1c82e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNDgzNzIsIm5iZiI6MTczNTM0ODA3MiwicGF0aCI6Ii8xNzg2Nzg1NjgvMzk4OTM0NjQ2LWIwNzM0NzllLWVkNWEtNDUwYS05ZmJkLTk0MjkyNGUxYzgyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyOFQwMTA3NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjc1MWY2MzYwMWRkYzhjZGY4NjlhMmMxNzgwYjhiNmE4N2MzZWVkOGMxMDBlYzEzM2FmODg0ZjEzNWQwZDY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RyBoQEX6v7KRSUvMfWPijvaOeeIbnCY3z8KqEpYFhD8) 在dt_previous_query_results数据库中把该场比赛数据删了重新获取就可以恢复正常

已推送版本1.3.0-pre.2增加判断尝试修复。对了看报错日志应该还没更新到1.3.0-pre吧？更新后需要追加cache服务并且因为缓存变动会多报一场最近的战报出来，我在更新日志中都提到了可以看一眼🫠

**Comment by zhoutongmike** [comment]
应该没问题了，我就先关了，ღ( ´･ᴗ･` )
